version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/BikeDashboard/BikeDashboard"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src/BikeDashboard/TestBikedashboard"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
