name: CI / CD 
on: 
  push:
  workflow_dispatch:
jobs: 
  Build-and-publish:
    name: Build, Test Publish
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test container
        run: |
          docker build -t andmos/bikedashboard:$(git rev-parse --short HEAD) .

      - name: Upload codecov report
        run: |
          docker create --name testfilecontainer andmos/bikedashboard:$(git rev-parse --short HEAD)
          docker cp testfilecontainer:/tmp/coverage.opencover.xml .
          bash <(curl -s https://codecov.io/bash)

      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker tag andmos/bikedashboard:$(git rev-parse --short HEAD) ghcr.io/andmos/bikedashboard:latest; 
          docker tag ghcr.io/andmos/bikedashboard:latest ghcr.io/andmos/bikedashboard:$(git rev-parse --short HEAD); 
          docker push ghcr.io/andmos/bikedashboard:$(git rev-parse --short HEAD); 
          docker push ghcr.io/andmos/bikedashboard:latest; 